---
title: Charting champions
hero_image: images/banner.png
description:
  Discover the power of lists in Python by creating an interactive chart
  of Olympic medals
meta_title: Python coding projects for kids and teens | Charting champions
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Discover the power of lists in Python by creating a chart of Olympic medals.
version: 4 
listed: false
copyedit: true
last_tested: "2021-10-07"
landing: true
steps:
  - title: Make a chart
  - title: Add data
    completion:
      - engaged
  - title: Add new lists
  - title: Large datasets
  - title: Split into lists
  - title: Load CSV into chart
    completion:
      - internal
  - title: Investigating data
  - title: GDP data
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Challenge
    challenge: true
